(()=>{
  const DB='jem_editor_v1',STORE='files',SKIP='jem_skip_editor',FLOW='jem_print_flow_v3',PDFJS='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',PDFWORKER='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
  const open=()=>new Promise((r,j)=>{const x=indexedDB.open(DB,1);x.onupgradeneeded=()=>x.result.createObjectStore(STORE);x.onsuccess=()=>r(x.result);x.onerror=()=>j(x.error)});
  const put=f=>open().then(db=>new Promise((r,j)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(f,'source');t.oncomplete=r;t.onerror=()=>j(t.error)}));
  const flow=()=>{try{return JSON.parse(localStorage.getItem(FLOW)||'{}')}catch{return{}}};
  const saveFlow=v=>localStorage.setItem(FLOW,JSON.stringify({...flow(),...v}));
  const api=()=>String((window.JEM_CONFIG||{}).API_BASE_URL||'').replace(/\/$/,'');
  let pdfPromise;
  const loadPdfJs=()=>{if(window.pdfjsLib)return Promise.resolve(window.pdfjsLib);if(pdfPromise)return pdfPromise;pdfPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=PDFJS;s.onload=()=>{if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc=PDFWORKER;resolve(window.pdfjsLib)}else reject(Error('PDF engine unavailable.'))};s.onerror=()=>reject(Error('Could not load PDF analysis engine.'));document.head.appendChild(s)});return pdfPromise};
  const countPdf=async file=>{const pdfjs=await loadPdfJs();const buf=await file.arrayBuffer();const pdf=await pdfjs.getDocument({data:buf}).promise;return pdf.numPages};
  const setMsg=t=>{const x=document.querySelector('#form-message');if(x)x.textContent=t};
  const setAnalyzer=async file=>{try{const n=file.type==='application/pdf'||/\.pdf$/i.test(file.name)?await countPdf(file):1;localStorage.setItem('jem_pdf_page_count',String(n));const p=document.querySelector('#analyzer-pages');if(p)p.textContent=`${n} page${n===1?'':'s'}`;const note=document.querySelector('#analyzer-note');if(note&&n>0)note.textContent=`${n} page${n===1?'':'s'} detected. You can select specific pages before payment.`;return n}catch(e){const old=Number(localStorage.getItem('jem_pdf_page_count')||0);if(old>0)return old;setMsg('Could not read this PDF. Please select another PDF.');throw e}};
  const uploadDirect=async b=>{const input=document.querySelector('#file'),file=input?.files?.[0];if(!file){setMsg('Please select a document first.');return}b.disabled=true;try{const pageCount=Number(localStorage.getItem('jem_pdf_page_count')||await setAnalyzer(file)||1);const fd=new FormData();fd.append('file',file);fd.append('pageCount',String(pageCount));fd.append('copies','1');fd.append('sides','single');fd.append('orientation','portrait');fd.append('paperSize','A4');fd.append('colorMode','BW');fd.append('pageRange','all');const base=api();if(!base)throw Error('Print service is temporarily unavailable.');setMsg('Uploading document…');const res=await fetch(base+'/api/print-requests',{method:'POST',body:fd});const text=await res.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:text}}if(!res.ok)throw Error(d.error||`Upload failed (HTTP ${res.status}).`);const id=d.id||d.orderId;if(!id)throw Error('Server did not return a request ID.');saveFlow({orderId:id,orderNumber:d.requestNumber||id,fileName:d.fileName||file.name,fileSize:file.size,pageCount:Number(d.pageCount||pageCount),status:d.status||'RECEIVED',paymentStatus:d.paymentStatus||'PENDING',amount:Number(d.amount||pageCount*5)});sessionStorage.removeItem(SKIP);location.assign('./settings.html')}catch(e){b.disabled=false;setMsg(e.message||'Upload failed. Please try again.')}};
  document.addEventListener('change',e=>{if(e.target?.id==='file'){const f=e.target.files?.[0];if(f){setAnalyzer(f).catch(()=>{})}}},true);
  document.addEventListener('click',async e=>{
    const skip=e.target.closest('#continue-without-editor');
    if(skip){e.preventDefault();e.stopImmediatePropagation();const b=document.querySelector('#to-step-2');if(!b||b.disabled)return;await uploadDirect(b);return}
    const b=e.target.closest('#to-step-2');if(!b)return;
    if(sessionStorage.getItem(SKIP)==='1'){sessionStorage.removeItem(SKIP);return}
    const input=document.querySelector('#file'),f=input?.files?.[0];if(!f)return;e.preventDefault();e.stopImmediatePropagation();try{b.disabled=true;setMsg('Opening document editor…');const n=await setAnalyzer(f);saveFlow({pageCount:n});await put(f);location.assign('./editor.html')}catch(err){b.disabled=false;setMsg(err.message||'Could not prepare the document. Please try again.')}}
  },true);
})();
