const FLOW_KEY='jem_print_flow_v2';
const UPI_ID='barkatkhanhindal6-1@okaxis';
const UPI_NAME='Jangira E-Mitra';
const PRICE_PER_PAGE=5;
const $=(s,r=document)=>r.querySelector(s);
const load=()=>{try{return JSON.parse(localStorage.getItem(FLOW_KEY)||'{}')}catch{return{}}};
const save=p=>{const n={...load(),...p};localStorage.setItem(FLOW_KEY,JSON.stringify(n));return n};
const go=n=>{location.assign(`${n}.html`)};
function overlay(text='Loading…',sub='Please wait'){
 let x=$('#page-loader');if(!x){x=document.createElement('div');x.id='page-loader';x.innerHTML='<div class="loader-box"><div class="loader-spinner"></div><strong id="loader-title"></strong><small id="loader-sub"></small></div>';document.body.appendChild(x)}
 x.querySelector('#loader-title').textContent=text;x.querySelector('#loader-sub').textContent=sub;x.classList.add('show');return x;
}
function hideLoader(){setTimeout(()=>$('#page-loader')?.classList.remove('show'),180)}
function parsePages(v,count){v=String(v||'all').trim().toLowerCase();if(!v||v==='all')return count||1;const set=new Set();for(const p of v.split(',')){if(/^\d+$/.test(p))set.add(+p);else if(/^\d+\s*-\s*\d+$/.test(p)){let[a,b]=p.split('-').map(Number);if(a>b)[a,b]=[b,a];for(let i=a;i<=b;i++)set.add(i)}}return set.size?set.size:null}
function note(s){return `Jangira Print | ${s.fileName||'Document'} | Pages: ${s.pageText==='all'?'All pages':s.pageText} | Copies: ${s.copies} | ${s.sides==='double'?'Double-sided':'Single-sided'} | ${s.orientation==='landscape'?'Landscape':'Portrait'}`}
function upi(amount,n){return `upi://pay?${new URLSearchParams({pa:UPI_ID,pn:UPI_NAME,tn:n,am:Number(amount).toFixed(2),cu:'INR'})}`}
function qr(link){return `https://api.qrserver.com/v1/create-qr-code/?size=360x360&margin=12&data=${encodeURIComponent(link)}`}
function pageBoot(){document.body.classList.add('page-ready');document.querySelectorAll('.reveal').forEach((e,i)=>setTimeout(()=>e.classList.add('visible'),80+i*45))}
function initUpload(){const f=$('#file');if(!f)return;const status=$('#file-status'),msg=$('#form-message'),next=$('#to-step-2');let selectedFile=null;const set=file=>{if(!file)return;if(file.size>20*1024*1024){msg.textContent='File size must be 20 MB or less.';next.disabled=true;return}if(!/\.(pdf|jpe?g|png)$/i.test(file.name)){msg.textContent='Only PDF, JPG, JPEG or PNG files are supported.';next.disabled=true;return}selectedFile=file;try{const d=new DataTransfer();d.items.add(file);f.files=d.files}catch{}status.querySelector('span:last-child').textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;status.classList.add('has-file');save({fileName:file.name,fileSize:file.size,pageCount:1});next.disabled=false;msg.textContent='Document ready.'};f.addEventListener('change',()=>set(f.files[0]));$('.dropzone')?.addEventListener('drop',e=>{e.preventDefault();set(e.dataTransfer.files[0])});next?.addEventListener('click',e=>{e.preventDefault();const s=load();if(!selectedFile&& !s.fileName){msg.textContent='Please select a document first.';return}if(selectedFile&&!s.fileName)save({fileName:selectedFile.name,fileSize:selectedFile.size,pageCount:1});next.disabled=true;overlay('Opening printer settings…','Preparing your print options');setTimeout(()=>go(2),350)})}
function initSettings(){const form=$('#print-form');if(!form)return;const s=load();if(!s.fileName)return go(1);if($('#selected-file'))$('#selected-file').textContent=s.fileName;form.elements.copies.value=s.copies||1;form.elements.sides.value=s.sides||'single';form.elements.orientation.value=s.orientation||'portrait';form.elements.pages.value=s.pageText||'all';const update=()=>{const p=String(form.elements.pages.value||'all').trim();const c=Math.max(1,Math.min(100,+form.elements.copies.value||1));const n=parsePages(p,s.pageCount||1);$('#estimate-price').textContent=n?`₹${n*c*PRICE_PER_PAGE}.00`:'Check page selection'};form.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',update));update();form.addEventListener('submit',e=>{e.preventDefault();const p=String(form.elements.pages.value||'all').trim();const copies=Math.max(1,Math.min(100,+form.elements.copies.value||1));const selected=parsePages(p,s.pageCount||1);if(!selected)return $('#form-message').textContent='Please enter valid pages.';save({pageText:p,copies,sides:form.elements.sides.value,orientation:form.elements.orientation.value,selectedCount:selected,amount:selected*copies*PRICE_PER_PAGE});overlay('Preparing payment…','Creating your payment session');setTimeout(()=>go(3),700)})}
function initPayment(){const a=$('#payment-amount');if(!a)return;const s=load();if(!s.fileName||!s.amount)return go(2);const n=note(s),link=upi(s.amount,n);a.textContent=`₹${Number(s.amount).toFixed(2)}`;if($('#upi-app-link'))$('#upi-app-link').href=link;const img=$('#upi-qr');if(img){img.classList.add('qr-blur');$('#qr-loading')?.classList.add('show');let done=false;const finish=()=>{if(done)return;done=true;img.classList.remove('qr-blur');$('#qr-loading')?.classList.remove('show');$('#qr-ready')?.classList.add('show')};img.onload=()=>{setTimeout(finish,5000)};img.src=qr(link);setTimeout(finish,5200)}let sec=120;const timer=$('#payment-timer');const tick=()=>{if(!timer)return;const m=String(Math.floor(sec/60)).padStart(2,'0'),x=String(sec%60).padStart(2,'0');timer.textContent=`${m}:${x}`;if(sec>0){sec--;setTimeout(tick,1000)}else{$('#to-step-4')?.setAttribute('disabled','disabled');$('#payment-expired')?.classList.add('show')}};tick();$('#to-step-4')?.addEventListener('click',()=>{overlay('Opening confirmation…','Moving to transaction details');setTimeout(()=>go(4),450)})}
function initConfirm(){const btn=$('#send-print-request');if(!btn)return;const s=load();if(!s.fileName||!s.amount)return go(2);for(const [id,text] of [['summary-amount',`₹${s.amount}.00`],['summary-file',s.fileName],['summary-pages',`${s.pageText} · ${s.copies} ${s.copies==1?'copy':'copies'}`],['summary-mode',`${s.sides==='double'?'Double':'Single'} · ${s.orientation==='landscape'?'Landscape':'Portrait'}`]])if($('#'+id))$('#'+id).textContent=text;btn.addEventListener('click',async()=>{const utr=String($('#utr')?.value||'').trim();if(utr.length<6)return $('#request-message').textContent='Please enter a valid UTR / transaction reference.';btn.disabled=true;overlay('Sending print request…','Submitting your payment reference');try{const cfg=window.JEM_CONFIG||{},API=String(cfg.API_BASE_URL||'').replace(/\/$/,'');if(API&&s.orderId){const p=await fetch(`${API}/api/orders/${encodeURIComponent(s.orderId)}/payment`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paid:true,utr})});if(!p.ok)throw Error('Payment confirmation failed.');const r=await fetch(`${API}/api/orders/${encodeURIComponent(s.orderId)}/send-print-request`,{method:'POST'});if(!r.ok)throw Error('Could not send print request.');const d=await r.json();save({utr,status:d.status||'AwaitingPaymentVerification',orderNumber:d.orderNumber||s.orderNumber})}else save({utr,status:'Received',orderNumber:s.orderNumber||`TEST-${Date.now()}`});setTimeout(()=>go(5),650)}catch(e){btn.disabled=false;hideLoader();$('#request-message').textContent=e.message||'Could not send request.'}})}
async function initStatus(){if(!$('#request-status-title'))return;const s=load();if(!s.fileName)return go(1);const render=st=>{const map={Received:['Request received','Your print request has been submitted.'],AwaitingPaymentVerification:['Payment submitted for verification','Your payment is waiting for operator verification.'],Approved:['Payment approved','Your print is approved and will enter the queue.'],Queued:['Waiting in print queue','Your job is waiting for the printer.'],Downloading:['Preparing document','Your document is being prepared.'],Validating:['Validating document','Checking your document before printing.'],Printing:['Printing in progress','Your document is being printed now.'],Completed:['Print completed','Your document has been printed successfully.'],Rejected:['Request rejected','Please contact Jangira E-Mitra.'],Failed:['Print failed','Please contact Jangira E-Mitra.']}[st]||['Request received','Your print request is being processed.'];$('#request-status-title').textContent=map[0];$('#request-status-text').textContent=map[1];$('#request-number').textContent=`Request ${s.orderNumber||s.orderId||'received'} · Status: ${st}`};render(s.status||'Received');const cfg=window.JEM_CONFIG||{},API=String(cfg.API_BASE_URL||'').replace(/\/$/,'');if(s.orderId&&API)setInterval(async()=>{try{const r=await fetch(`${API}/api/orders/${encodeURIComponent(s.orderId)}`);if(r.ok){const o=await r.json();save({status:o.status,orderNumber:o.orderNumber||s.orderNumber});render(o.status)}}catch{}},5000);$('#new-print')?.addEventListener('click',()=>{localStorage.removeItem(FLOW_KEY);overlay('Starting new print…','Resetting your print session');setTimeout(()=>go(1),500)})}
initUpload();initSettings();initPayment();initConfirm();initStatus();pageBoot();