const FLOW_KEY='jem_print_flow_v3';
const UPI_ID='barkatkhanhindal6-1@okaxis';
const UPI_NAME='Jangira E-Mitra';
const PRICE_PER_PAGE=5;
const MAX_FILE=50*1024*1024;
const $=(s,r=document)=>r.querySelector(s);
const load=()=>{try{return JSON.parse(localStorage.getItem(FLOW_KEY)||'{}')}catch{return{}}};
const save=p=>{const n={...load(),...p};localStorage.setItem(FLOW_KEY,JSON.stringify(n));return n};
const STEP_PAGES={1:'upload.html',2:'settings.html',3:'payment.html',4:'confirm.html',5:'status.html'};
const go=n=>window.location.assign(`./${STEP_PAGES[n]||STEP_PAGES[1]}`);
const api=()=>String((window.JEM_CONFIG||{}).API_BASE_URL||'').replace(/\/$/,'');
function loadEnhancements(){if(document.querySelector('link[data-jem-enhancements]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./enhancements.css?v=20260903a';l.dataset.jemEnhancements='1';document.head.appendChild(l)}
async function jsonFetch(url,options={}){const r=await fetch(url,options);const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:text}}if(!r.ok)throw new Error(d.error||'Request failed.');return d}
function overlay(text='Loading…',sub='Please wait'){let x=$('#page-loader');if(!x){x=document.createElement('div');x.id='page-loader';x.className='page-loader';document.body.appendChild(x)}if(!x.querySelector('.loader-box'))x.innerHTML='<div class="loader-box"><div class="loader-spinner"></div><strong class="loader-title"></strong><small class="loader-sub"></small></div>';x.querySelector('.loader-title').textContent=text;x.querySelector('.loader-sub').textContent=sub;x.classList.add('show');return x}
function hideLoader(){setTimeout(()=>$('#page-loader')?.classList.remove('show'),120)}
function parsePages(v,count){v=String(v||'all').trim().toLowerCase();if(!v||v==='all')return count||1;const set=new Set();for(const p of v.split(',')){if(/^\d+$/.test(p)){const n=+p;if(n<1||n>count)return null;set.add(n)}else if(/^\d+\s*-\s*\d+$/.test(p)){let[a,b]=p.split('-').map(Number);if(a>b)[a,b]=[b,a];if(a<1||b>count)return null;for(let i=a;i<=b;i++)set.add(i)}else return null}return set.size?set.size:null}
function note(s){return `Jangira Print | ${s.fileName||'Document'} | Pages: ${s.pageText==='all'?'All pages':s.pageText} | Copies: ${s.copies} | ${s.sides==='double'?'Double-sided':'Single-sided'} | ${s.orientation==='landscape'?'Landscape':'Portrait'}`}
function upi(amount,n){return `upi://pay?${new URLSearchParams({pa:UPI_ID,pn:UPI_NAME,tn:n,am:Number(amount).toFixed(2),cu:'INR'})}`}
function qr(link){return `https://api.qrserver.com/v1/create-qr-code/?size=360x360&margin=12&data=${encodeURIComponent(link)}`}
function pageBoot(){loadEnhancements();document.body.classList.add('page-ready');document.querySelectorAll('.reveal').forEach((e,i)=>setTimeout(()=>e.classList.add('visible'),80+i*45))}
async function initUpload(){const f=$('#file');if(!f)return;const status=$('#file-status'),msg=$('#form-message'),next=$('#to-step-2');let selectedFile=null;const set=async file=>{if(!file)return;if(file.size>MAX_FILE){msg.textContent='File size must be 50 MB or less.';next.disabled=true;return}if(!/\.(pdf|jpe?g|png)$/i.test(file.name)){msg.textContent='Only PDF, JPG, JPEG or PNG files are supported.';next.disabled=true;return}selectedFile=file;try{const d=new DataTransfer();d.items.add(file);f.files=d.files}catch{}status.querySelector('span:last-child').textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;status.classList.add('has-file');msg.textContent='Document ready. Click continue to upload securely.';next.disabled=false};f.addEventListener('change',()=>set(f.files[0]));$('.dropzone')?.addEventListener('dragover',e=>{e.preventDefault();$('.dropzone')?.classList.add('dragging')});$('.dropzone')?.addEventListener('dragleave',()=>$('.dropzone')?.classList.remove('dragging'));$('.dropzone')?.addEventListener('drop',e=>{e.preventDefault();$('.dropzone')?.classList.remove('dragging');set(e.dataTransfer.files[0])});next.addEventListener('click',async e=>{e.preventDefault();if(!selectedFile){msg.textContent='Please select a document first.';return}const API=api();if(!API){msg.textContent='Print service is temporarily unavailable.';return}next.disabled=true;overlay('Uploading document…','Securely sending your file to Jangira E-Mitra');try{const form=new FormData();form.append('file',selectedFile);form.append('pageCount','1');form.append('copies','1');form.append('sides','single');form.append('orientation','portrait');form.append('paperSize','A4');form.append('colorMode','BW');form.append('pageRange','all');const d=await jsonFetch(`${API}/api/print-requests`,{method:'POST',body:form});const orderId=d.orderId||d.id;save({orderId,orderNumber:d.requestNumber||orderId,fileName:d.fileName||selectedFile.name,fileSize:selectedFile.size,pageCount:Number(d.pageCount||1),status:d.status||'RECEIVED',paymentStatus:d.paymentStatus||'PENDING',amount:Number(d.amount||5)});if(!orderId)throw new Error('Server did not return a request ID.');go(2)}catch(err){next.disabled=false;hideLoader();msg.textContent=err.message||'Upload failed. Please try again.'}})}
function initSettings(){const form=$('#print-form');if(!form)return;const s=load();if(!s.fileName||!s.orderId)return go(1);if($('#selected-file'))$('#selected-file').textContent=s.fileName;form.elements.copies.value=s.copies||1;form.elements.sides.value=s.sides||'single';form.elements.orientation.value=s.orientation||'portrait';form.elements.pages.value=s.pageText||'all';const update=()=>{const p=String(form.elements.pages.value||'all').trim();const c=Math.max(1,Math.min(100,+form.elements.copies.value||1));const n=parsePages(p,s.pageCount||1);$('#estimate-price').textContent=n?`₹${n*c*PRICE_PER_PAGE}.00`:'Check page selection'};form.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',update));update();form.addEventListener('submit',async e=>{e.preventDefault();const p=String(form.elements.pages.value||'all').trim();const copies=Math.max(1,Math.min(100,+form.elements.copies.value||1));const selected=parsePages(p,s.pageCount||1);const msg=$('#form-message');if(!selected){msg.textContent='Please enter valid pages.';return}const API=api();if(!API){msg.textContent='Print service is temporarily unavailable.';return}const button=form.querySelector('button[type=submit]');button.disabled=true;overlay('Saving print settings…','Updating your order securely');try{const d=await jsonFetch(`${API}/api/print-requests/${encodeURIComponent(s.orderId)}/settings`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({copies,sides:form.elements.sides.value,orientation:form.elements.orientation.value,pageRange:p,paperSize:'A4',colorMode:'BW'})});save({pageText:p,copies,sides:form.elements.sides.value,orientation:form.elements.orientation.value,selectedCount:selected,amount:Number(d.amount??selected*copies*PRICE_PER_PAGE)});go(3)}catch(err){button.disabled=false;hideLoader();msg.textContent=err.message||'Could not save settings.'}})}
function initPayment(){const a=$('#payment-amount');if(!a)return;const s=load();if(!s.fileName||!s.orderId||!s.amount)return go(2);const n=note(s),link=upi(s.amount,n);a.textContent=`₹${Number(s.amount).toFixed(2)}`;$('#upi-app-link')?.setAttribute('href',link);const img=$('#upi-qr');if(img){img.classList.add('qr-blur');$('#qr-loading')?.classList.add('show');let done=false;const finish=()=>{if(done)return;done=true;img.classList.remove('qr-blur');$('#qr-loading')?.classList.remove('show');$('#qr-ready')?.classList.add('show')};img.onload=()=>setTimeout(finish,900);img.onerror=finish;img.src=qr(link);setTimeout(finish,3000)}let sec=120;const timer=$('#payment-timer');const tick=()=>{if(!timer)return;timer.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec>0)setTimeout(()=>{sec--;tick()},1000);else{$('#to-step-4')?.setAttribute('disabled','disabled');$('#payment-expired')?.classList.add('show')}};tick();$('#to-step-4')?.addEventListener('click',()=>{overlay('Opening confirmation…','Enter your UPI transaction reference');setTimeout(()=>go(4),120)})}
function initConfirm(){const btn=$('#send-print-request');if(!btn)return;const s=load();if(!s.fileName||!s.orderId||!s.amount)return go(2);for(const [id,text] of [['summary-amount',`₹${Number(s.amount).toFixed(2)}`],['summary-file',s.fileName],['summary-pages',`${s.pageText||'all'} · ${s.copies} ${s.copies==1?'copy':'copies'}`],['summary-mode',`${s.sides==='double'?'Double':'Single'} · ${s.orientation==='landscape'?'Landscape':'Portrait'}`]])if($('#'+id))$('#'+id).textContent=text;btn.addEventListener('click',async()=>{const utr=String($('#utr')?.value||'').trim(),rm=$('#request-message');if(utr.length<6){if(rm)rm.textContent='Please enter a valid UTR / transaction reference.';return}const API=api();if(!API){rm.textContent='Print service is temporarily unavailable.';return}btn.disabled=true;overlay('Submitting print request…','Recording your payment reference securely');try{const d=await jsonFetch(`${API}/api/print-requests/${encodeURIComponent(s.orderId)}/payment`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({utr})});save({utr,status:d.status||'PAYMENT_PENDING',paymentStatus:d.paymentStatus||'PENDING'});go(5)}catch(err){btn.disabled=false;hideLoader();rm.textContent=err.message||'Could not submit request.'}})}
async function initStatus(){if(!$('#request-status-title'))return;const s=load();if(!s.fileName||!s.orderId)return go(1);const API=api();const render=(st,queue)=>{const map={RECEIVED:['Request received','Your print request has been submitted.'],PAYMENT_PENDING:['Payment submitted for verification','Your payment is waiting for operator verification.'],REVIEWING:['Document under review','The operator is checking your document.'],APPROVED:['Payment approved','Your print is approved and will enter the queue.'],QUEUED_FOR_PRINTING:['Waiting in print queue','Your job is waiting for the printer.'],PRINTING:['Printing in progress','Your document is being printed now.'],COMPLETED:['Print completed','Your document has been printed successfully.'],REJECTED:['Request rejected','Please contact Jangira E-Mitra.'],FAILED:['Print failed','Please contact Jangira E-Mitra.'],CANCELLED:['Request cancelled','Please contact Jangira E-Mitra.']}[st]||['Request received','Your print request is being processed.'];$('#request-status-title').textContent=map[0];$('#request-status-text').textContent=queue>0?`${map[1]} Queue position: ${queue}.`:map[1];$('#request-number').textContent=`Request ${s.orderNumber||s.orderId} · Status: ${st}`};let last='';const poll=async()=>{try{const d=await jsonFetch(`${API}/api/print-requests/${encodeURIComponent(s.orderId)}`);save({status:d.status,orderNumber:d.requestNumber||s.orderNumber,queuePosition:d.queuePosition});render(d.status,Number(d.queuePosition||0));last=d.status}catch{if(!last)render(s.status||'RECEIVED',s.queuePosition||0)}};await poll();const timer=setInterval(poll,3000);$('#new-print')?.addEventListener('click',()=>{clearInterval(timer);localStorage.removeItem(FLOW_KEY);overlay('Starting new print…','Resetting your print session');setTimeout(()=>go(1),120)})}
initUpload();initSettings();initPayment();initConfirm();initStatus();pageBoot();