(()=>{
const KEY='jem_print_settings_v1',FLOW='jem_print_flow_v3',PDFJS='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
const $=(s,r=document)=>r.querySelector(s),flow=()=>{try{return JSON.parse(localStorage.getItem(FLOW)||'{}')}catch{return{}}},save=v=>{let n={};try{n=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};n={...n,...v};localStorage.setItem(KEY,JSON.stringify(n));return n};
const parse=(v,c)=>{v=String(v||'all').trim().toLowerCase();if(!v||v==='all')return Array.from({length:c},(_,i)=>i+1);const s=new Set;for(const x of v.split(',')){if(/^\d+$/.test(x)){const n=+x;if(n<1||n>c)return null;s.add(n)}else if(/^\d+\s*-\s*\d+$/.test(x)){let[a,b]=x.split('-').map(Number);if(a>b)[a,b]=[b,a];if(a<1||b>c)return null;for(let i=a;i<=b;i++)s.add(i)}else return null}return [...s].sort((a,b)=>a-b)};
async function getSource(){const db=await new Promise((ok,no)=>{const r=indexedDB.open('jem_editor_v1',2);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const r=db.transaction('files','readonly').objectStore('files').get('source');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function loadPdfJs(){return new Promise((ok,no)=>{if(window.pdfjsLib)return ok();const s=document.createElement('script');s.src=PDFJS;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function enhance(){const form=$('#print-form'),stage=$('.preview-stage'),paper=$('#paper-preview');if(!form||!stage||!paper)return;const src=await getSource().catch(()=>null);paper.innerHTML='<canvas id="real-preview-canvas"></canvas><div id="preview-loading" class="preview-loading">Loading actual document…</div>';const canvas=$('#real-preview-canvas'),ctx=canvas.getContext('2d');let pdf=null,img=null,url=null;try{if(src?.type==='pdf'){await loadPdfJs();pdf=await pdfjsLib.getDocument({data:src.bytes}).promise}else if(src?.type==='image'){img=new Image;url=URL.createObjectURL(src.blob);await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url})}else throw Error('missing')}catch(e){$('#preview-loading').textContent='Actual document preview unavailable';return}const total=pdf?pdf.numPages:1;let pos=1;
const render=async()=>{const pages=parse(form.elements.pages.value,total)||[];if(!pages.length)return;pos=Math.min(pos,pages.length);const pageNo=pages[pos-1],loading=$('#preview-loading');loading.style.display='flex';let w=0,h=0;if(pdf){const p=await pdf.getPage(pageNo),base=p.getViewport({scale:1}),maxW=Math.max(180,Math.min(620,stage.clientWidth-36)),scale=Math.min(maxW/base.width,620/base.height),v=p.getViewport({scale,rotation:form.elements.orientation.value==='landscape'?90:0});w=v.width;h=v.height;canvas.width=Math.ceil(w);canvas.height=Math.ceil(h);ctx.clearRect(0,0,w,h);ctx.save();ctx.filter='grayscale(1)';await p.render({canvasContext:ctx,viewport:v}).promise;ctx.restore()}else{const maxW=Math.min(620,stage.clientWidth-36),ratio=img.naturalWidth/img.naturalHeight;w=Math.min(maxW,img.naturalWidth);h=w/ratio;canvas.width=Math.ceil(w);canvas.height=Math.ceil(h);ctx.save();ctx.filter='grayscale(1)';ctx.drawImage(img,0,0,w,h);ctx.restore()}
paper.className='paper-preview '+(form.elements.orientation.value==='landscape'?'landscape':'portrait');paper.style.width=Math.min(w,620)+'px';paper.style.height=Math.min(h,620)+'px';paper.style.aspectRatio='auto';loading.style.display='none';$('#preview-page-number').textContent=`Page ${pageNo} of ${total}`;$('#preview-page-label').textContent=`Preview page ${pos} of ${pages.length} · Document page ${pageNo}`;$('#preview-page-range').textContent=`Document page ${pageNo}`;$('#preview-paper').textContent=form.elements.paperSize.value;$('#preview-orientation').textContent=form.elements.orientation.value==='landscape'?'Landscape':'Portrait';$('#preview-sides').textContent=form.elements.sides.value==='double'?'Double-sided':'Single-sided';$('#preview-copies').textContent=form.elements.copies.value;$('#preview-badge').textContent=`${form.elements.copies.value} ${+form.elements.copies.value===1?'COPY':'COPIES'}`;$('#preview-prev').disabled=pos<=1;$('#preview-next').disabled=pos>=pages.length;};
const refresh=()=>{const pages=parse(form.elements.pages.value,total),c=Math.max(1,Math.min(100,+form.elements.copies.value||1));$('#estimate-price').textContent=pages?`₹${pages.length*c*5}.00`:'Check page selection';const p=String(form.elements.pages.value||'all').trim();$('#settings-preview').textContent=`${form.elements.paperSize.value} · ${form.elements.orientation.value==='landscape'?'Landscape':'Portrait'} · ${form.elements.sides.value==='double'?'Double-sided':'Single-sided'} · ${c} ${c===1?'copy':'copies'} · ${p==='all'?'All pages':p}`;save({paperSize:form.elements.paperSize.value,pageText:p,copies:c,sides:form.elements.sides.value,orientation:form.elements.orientation.value});render()};
$('#preview-prev')?.addEventListener('click',()=>{pos=Math.max(1,pos-1);render()});$('#preview-next')?.addEventListener('click',()=>{pos=Math.min((parse(form.elements.pages.value,total)||[]).length,pos+1);render()});form.querySelectorAll('input,select').forEach(e=>{e.addEventListener('input',refresh);e.addEventListener('change',refresh)});refresh();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();