(()=>{
  const KEY='jem_print_settings_v1',FLOW='jem_print_flow_v3';
  const $=(s,r=document)=>r.querySelector(s);
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
  const flow=()=>{try{return JSON.parse(localStorage.getItem(FLOW)||'{}')}catch{return{}}};
  const save=v=>{const n={...load(),...v};localStorage.setItem(KEY,JSON.stringify(n));return n};
  const fire=el=>el.dispatchEvent(new Event('input',{bubbles:true}));
  const enhance=()=>{
    const form=$('#print-form');if(!form)return;
    const s=load(),f=flow(),count=Math.max(1,Number(f.pageCount||1));
    if(form.elements.paperSize)form.elements.paperSize.value=s.paperSize||'A4';
    const pagesInput=form.elements.pages;
    if(pagesInput&&!$('#page-selector')){
      const box=document.createElement('div');box.id='page-selector';box.style.cssText='margin-top:12px;padding:13px;border:1px solid #e5e0d6;border-radius:14px;background:#faf8f3';
      box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><strong style="font-size:12px">Quick page selection</strong><span id="page-selector-count" style="font-size:10px;color:#77736c;font-weight:800">${count} pages detected</span></div><div style="display:flex;gap:8px;margin-top:10px;flex-wrap:wrap"><button type="button" id="select-all-pages" class="skip-editor">All pages</button><input id="single-page-input" type="number" min="1" max="${count}" placeholder="Page no." style="width:110px;border:1px solid #ddd8ce;border-radius:10px;padding:10px;background:#fff"><button type="button" id="add-single-page" class="button primary" style="padding:10px 13px">Select page</button></div><div id="page-chips" style="display:flex;gap:6px;flex-wrap:wrap;margin-top:10px;max-height:150px;overflow:auto"></div><small style="display:block;margin-top:9px;color:#77736c;line-height:1.45">Select pages or type ranges such as 1-4, 7, 9 below.</small>`;
      const rangeRow=form.querySelector('.range-row');if(rangeRow)rangeRow.insertAdjacentElement('afterend',box);else form.insertBefore(box,form.firstChild);
      const chips=$('#page-chips');
      const parse=v=>{const set=new Set(),raw=String(v||'all').trim().toLowerCase();if(raw==='all'||!raw)return set;for(const part of raw.split(',')){if(/^\d+$/.test(part))set.add(+part);else if(/^\d+\s*-\s*\d+$/.test(part)){let[a,b]=part.split('-').map(Number);if(a>b)[a,b]=[b,a];for(let i=a;i<=b&&i<=count;i++)if(i>0)set.add(i)}}return set};
      const renderChips=()=>{chips.innerHTML='';const selected=parse(pagesInput.value);const all=String(pagesInput.value||'all').trim().toLowerCase()==='all';for(let i=1;i<=Math.min(count,200);i++){const b=document.createElement('button');b.type='button';b.textContent=i;const on=all||selected.has(i);b.style.cssText=`min-width:34px;height:32px;border:1px solid #ddd8ce;border-radius:8px;background:${on?'#151513':'#fff'};color:${on?'#fff':'#333'};font-size:11px;font-weight:800;cursor:pointer`;b.onclick=()=>{let set=parse(pagesInput.value);if(all)set=new Set();if(set.has(i))set.delete(i);else set.add(i);pagesInput.value=[...set].sort((a,b)=>a-b).join(',')||'all';fire(pagesInput);renderChips()};chips.appendChild(b)}};
      $('#select-all-pages').onclick=()=>{pagesInput.value='all';fire(pagesInput);renderChips()};
      $('#add-single-page').onclick=()=>{const n=Number($('#single-page-input').value);if(!Number.isInteger(n)||n<1||n>count)return;let set=parse(pagesInput.value);set.add(n);pagesInput.value=[...set].sort((a,b)=>a-b).join(',');fire(pagesInput);renderChips();$('#single-page-input').value=''};
      renderChips();pagesInput.addEventListener('input',renderChips);
    }
    const parsePages=v=>{const raw=String(v||'all').trim().toLowerCase();if(!raw||raw==='all')return count;const set=new Set();for(const part of raw.split(',')){if(/^\d+$/.test(part)){const n=+part;if(n<1||n>count)return 0;set.add(n)}else if(/^\d+\s*-\s*\d+$/.test(part)){let[a,b]=part.split('-').map(Number);if(a>b)[a,b]=[b,a];if(a<1||b>count)return 0;for(let i=a;i<=b;i++)set.add(i)}else return 0}return set.size};
    let previewPage=1;
    const refresh=()=>{const pages=String(form.elements.pages.value||'all').trim();const copies=Math.max(1,Math.min(100,+form.elements.copies.value||1));const paper=form.elements.paperSize.value;const side=form.elements.sides.value==='double'?'Double-sided':'Single-sided';const orientation=form.elements.orientation.value==='landscape'?'Landscape':'Portrait';const selected=parsePages(pages);const price=selected?selected*copies*5:0;$('#estimate-price').textContent=selected?`₹${price.toFixed(2)}`:'Check page selection';$('#settings-preview').textContent=`${paper} · ${orientation} · ${side} · ${copies} ${copies===1?'copy':'copies'} · ${pages==='all'?'All pages':pages}`;save({paperSize:paper,pageText:pages,copies,sides:form.elements.sides.value,orientation:form.elements.orientation.value});
      const pp=$('#paper-preview');if(pp){pp.classList.toggle('portrait',orientation==='portrait');pp.classList.toggle('landscape',orientation==='landscape');pp.classList.toggle('a5',paper==='A5');pp.classList.toggle('letter',paper==='Letter');$('#preview-paper').textContent=paper;$('#preview-orientation').textContent=orientation;$('#preview-sides').textContent=side;$('#preview-copies').textContent=copies;$('#preview-badge').textContent=`${copies} ${copies===1?'COPY':'COPIES'}`;$('#preview-page-range').textContent=pages==='all'?'All pages':pages;$('#preview-page-number').textContent=`Page ${previewPage} of ${count}`;$('#preview-page-label').textContent=`Preview page ${previewPage} of ${count}`;$('#preview-overlay').textContent=side==='Double-sided'?(previewPage%2?'FRONT':'BACK'):'';$('#preview-text').innerHTML=`Document preview<br><b>${pages==='all'?'All pages':pages}</b><br>${side} · ${orientation}`;$('#preview-prev').disabled=previewPage<=1;$('#preview-next').disabled=previewPage>=count}}
    $('#preview-prev')?.addEventListener('click',()=>{if(previewPage>1){previewPage--;refresh()}});$('#preview-next')?.addEventListener('click',()=>{if(previewPage<count){previewPage++;refresh()}});
    form.querySelectorAll('input,select').forEach(e=>{e.addEventListener('change',refresh);e.addEventListener('input',refresh)});refresh();
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();