(()=>{
const PDFLIB='https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js';
let pdfPromise;
const loadPdfLib=()=>{if(window.PDFLib)return Promise.resolve(window.PDFLib);if(pdfPromise)return pdfPromise;pdfPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=PDFLIB;s.onload=()=>window.PDFLib?resolve(window.PDFLib):reject(Error('Watermark engine unavailable.'));s.onerror=()=>reject(Error('Could not load watermark engine.'));document.head.appendChild(s)});return pdfPromise};
const isPdf=f=>/\.pdf$/i.test(f.name)||f.type==='application/pdf';
const image=async file=>{const bmp=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;const c=canvas.getContext('2d');c.drawImage(bmp,0,0);bmp.close?.();const size=Math.max(12,Math.round(Math.min(canvas.width,canvas.height)*.025));c.save();c.globalAlpha=.48;c.fillStyle='#777';c.font=`italic ${size}px Arial`;c.textAlign='right';c.textBaseline='bottom';c.fillText('Jangira AutoPrint',canvas.width-Math.max(12,size*.7),canvas.height-Math.max(10,size*.65));c.restore();const blob=await new Promise(r=>canvas.toBlob(r,file.type==='image/png'?'image/png':'image/jpeg',.94));return new File([blob],file.name,{type:blob.type,lastModified:file.lastModified})};
const pdf=async file=>{const {PDFDocument,StandardFonts,rgb}=await loadPdfLib();const doc=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});const font=await doc.embedFont(StandardFonts.HelveticaOblique);for(const p of doc.getPages()){const {width,height}=p.getSize();const size=Math.max(7,Math.min(11,width*.018));const text='Jangira AutoPrint';const tw=font.widthOfTextAtSize(text,size);p.drawText(text,{x:Math.max(6,width-tw-10),y:7,size,font,color:rgb(.45,.45,.45),opacity:.48});}const bytes=await doc.save({useObjectStreams:true});return new File([bytes],file.name,{type:'application/pdf',lastModified:file.lastModified})};
window.JEMWatermark={async apply(file){if(!file)return file;if(file.__jemWatermarked)return file;let out;if(isPdf(file))out=await pdf(file);else if(/^image\/(jpeg|png)$/i.test(file.type)||/\.(jpe?g|png)$/i.test(file.name))out=await image(file);else return file;try{Object.defineProperty(out,'__jemWatermarked',{value:true});}catch{}return out}};
})();
